/**
 * The mock neobank's own COSE identity public key, pinned into the app binary so
 * a payer can verify a server-signed COSE_Sign1 receipt without a network round
 * trip (Mode B, spec §5, and every mode's receipt verification generally). This
 * is the one deliberate exception to "no secrets ship in the app binary"
 * (CLAUDE.md §6) -- it's a public key verifying receipts, not a secret.
 *
 * Generated by `pnpm --filter server generate-server-key` (M1 Step 5) against
 * this dev environment's server/keys/server_identity.pem (gitignored, never
 * committed). Re-pin this value whenever that key is regenerated -- an app built
 * against a stale value will fail to verify every receipt from a server running
 * the new key.
 */

/** Raw 33-byte SEC1-compressed P-256 public key, hex-encoded. */
export const SERVER_PUBLIC_KEY_HEX = "02211e76437c52cdaacd6311e225c93b8dc3b4860c831edb5e895db66dcb3e38ec";

export function getServerPublicKeyBytes(): Uint8Array {
  const bytes = new Uint8Array(SERVER_PUBLIC_KEY_HEX.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = Number.parseInt(SERVER_PUBLIC_KEY_HEX.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}
