#!/usr/bin/env bash
# Ship List v2 Phase 7 -- one-time (per environment) generation of the
# Android release-signing keystore. CLAUDE.md states "release builds are
# signed with a dedicated keystore" as a rule; today's actual
# android/app/build.gradle (regenerated by `expo prebuild`, gitignored)
# signs its `release` buildType with the DEBUG keystore -- this script,
# eas.json's `credentialsSource: "local"` production profile, and the
# resulting credentials.json are what closes that gap, matching this
# project's existing "generate locally, gitignore the secret" pattern
# (server/scripts/generate-server-key.ts, caddy/certs/'s mkcert step).
#
# Refuses to overwrite an existing keystore -- regenerating silently would
# invalidate every previously-issued release's upgrade path (Android
# requires the same signing key across an app's update history).
set -euo pipefail

cd "$(dirname "$0")/.."

KEYSTORE_DIR="credentials"
KEYSTORE_PATH="$KEYSTORE_DIR/release.jks"
CREDENTIALS_JSON="credentials.json"
ALIAS="tappay-release"

if [[ -f "$KEYSTORE_PATH" ]]; then
  echo "refusing to overwrite existing keystore at $KEYSTORE_PATH" >&2
  exit 1
fi

if ! command -v keytool >/dev/null 2>&1; then
  echo "keytool not found -- it ships with the JDK (CLAUDE.md §6 already assumes JDK 17)" >&2
  exit 1
fi

mkdir -p "$KEYSTORE_DIR"

# Strong random password, not a typed-in or hardcoded value -- this is a
# real production signing key, not a dev-only placeholder like
# APP_DB_PASSWORD/JWT_SECRET's documented "dev-only-change-me" convention.
# openssl rand, not Math.random-shaped, for the same reason CLAUDE.md's
# crypto invariants (§5) always specify a real CSPRNG.
#
# One password, not two: modern `keytool` defaults to a PKCS12 keystore
# (JKS is legacy/deprecated), and PKCS12 does not support a store password
# distinct from its key password -- passing two different values doesn't
# error, it silently ignores -keypass and uses -storepass for both, which
# would have shipped a wrong (never-actually-used) keyPassword into
# credentials.json. Found by direct verification (checking keytool's own
# warning output), not assumed from documentation -- one shared password
# is the only value that's actually correct here.
PASSWORD="$(openssl rand -base64 24)"

keytool -genkeypair -v \
  -keystore "$KEYSTORE_PATH" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -storepass "$PASSWORD" \
  -keypass "$PASSWORD" \
  -dname "CN=TapPay, OU=Engineering, O=TapPay, L=, ST=, C=MA"

cat > "$CREDENTIALS_JSON" <<EOF
{
  "android": {
    "keystore": {
      "keystorePath": "$KEYSTORE_PATH",
      "keystorePassword": "$PASSWORD",
      "keyAlias": "$ALIAS",
      "keyPassword": "$PASSWORD"
    }
  }
}
EOF

echo
echo "Keystore written to $KEYSTORE_PATH"
echo "credentials.json written (gitignored -- see mobile/.gitignore)"
echo
echo "IMPORTANT: $KEYSTORE_PATH and $CREDENTIALS_JSON are the only copies of this"
echo "signing key. Losing them means every future release build must ship as a"
echo "new, unrelated app listing -- Android has no recovery path for a lost"
echo "release key. Back both up into a real secret manager now (the store/key"
echo "passwords currently live in plaintext in $CREDENTIALS_JSON, which is fine"
echo "as EAS's own local-credentials format but is not itself a backup)."
