/** The IBankAdapter seam (spec §2.1). A real bank would implement this with zero
 * changes above it — MockBankAdapter (server/src/adapters) is the only implementation
 * for MVP. Money is always bigint minor units; never a float anywhere in this file.
 */

export interface ReservationResult {
  success: boolean;
  reservationId?: string;
  failureReason?: string;
}

export interface CommitResult {
  success: boolean;
  settledAt: Date;
  /** COSE_Sign1 bytes, signed by the server identity key (packages/shared/src/crypto). */
  receiptSignature: Uint8Array;
  failureReason?: string;
}

/** Binds a settlement's receipt to its intended recipient (TxReceipt's
 * `recipient_device_id`/`receiver_nonce`) -- additive and optional so this
 * doesn't break the seam's "a real bank would implement this with zero
 * changes above it" contract; a caller that omits it just gets a receipt
 * with no recipient binding, which reserve()/commit()'s bare-reservation
 * path (no device-level context available at all) is the only current
 * example of.
 *
 * `reference` (v2, docs/TapPay_v2_Technical_Design.md §4): the human-readable
 * reference/reason string on a plain neobank transfer -- optional for the
 * same reason the device fields are: the parked P2P proximity path
 * (server/src/parked/routes/tx-cose.ts) never supplies one, and the seam's
 * "zero changes above it" contract means adding a field can't force every
 * existing caller to start passing it. */
export interface TransferContext {
  recipientDeviceId?: Uint8Array;
  receiverNonce?: Uint8Array;
  reference?: string;
}

export interface IBankAdapter {
  getAvailableBalance(accountId: string, currency: string): Promise<bigint>;
  reserve(
    txUuid: string,
    accountId: string,
    amount: bigint,
    currency: string,
    ttlSeconds: number,
  ): Promise<ReservationResult>;
  commit(txUuid: string): Promise<CommitResult>;
  release(txUuid: string): Promise<void>;
  transfer(
    txUuid: string,
    fromAccountId: string,
    toAccountId: string,
    amount: bigint,
    currency: string,
    context?: TransferContext,
  ): Promise<CommitResult>;
}

/** Stub for M2 — evaluateConnectivity() ships with Mode B/C in the M2 milestone. */
export enum ConnectivityMode {
  MODE_A = "RECEIVER_ONLINE",
  MODE_B = "SENDER_ONLINE",
  MODE_C = "BOTH_OFFLINE",
}

/**
 * The payload CBOR-encoded inside the COSE_Sign1 signature (packages/shared/src/crypto/cose.ts).
 * Device ids and tx_uuid are raw 16-byte UUID bytes, not string form, to keep the
 * signed payload (and the QR code carrying it, per M1 Step 9) small — string UUIDs
 * would cost more than double for no security benefit.
 *
 * `ts` freshness policy (decided in M1 planning, not left decorative): the server
 * rejects proposals whose `ts` falls outside a generous, config-driven window at
 * /tx/submit. This is a coarse sanity bound, layered *behind* tx_uuid idempotency
 * (the actual replay defense) — not a replacement for it. Kept consistent with
 * Mode C's 24h freshness_token concept arriving in M2.
 */
export interface TxProposal {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  recipient_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string; // ISO 4217-style, 3 chars, "MAD" for MVP
  receiver_nonce: Uint8Array; // 16 bytes, generated by the payee (Request QR)
  ts: number; // unix ms
}

/**
 * The payee's "Request" QR payload (unsigned, by design -- the payer's
 * TxProposal is what's cryptographically bound to a transaction; this is
 * just an invitation carrying the nonce that proposal must embed). Moved
 * here from mobile/src/transport/qr.ts (Phase 4) so the unified payment flow
 * (mobile/src/payments/paymentFlow.ts) can be exercised by this package's
 * test suite -- mobile has no test runner of its own (`lint` is
 * `tsc --noEmit` only).
 *
 * `receiver_online` is new here (the mobile-local version never had it): the
 * payee's own self-assessed `GET /health` probe result at the moment they
 * generated this QR, stamped in so the payer's mode-selection
 * (evaluateConnectivity) has a receiver-side signal to combine with its own
 * probe. It is a HINT only, never trusted for anything security-relevant --
 * it only picks a choreography (Mode A/B/C); every choreography stays
 * independently safe regardless of what this field claims (see TxReceipt's
 * doc comment and the transfer()-level tx_uuid conflict guard for why).
 */
export interface TxRequest {
  recipient_device_id: Uint8Array; // 16 bytes
  receiver_nonce: Uint8Array; // 16 bytes
  ts: number; // unix ms
  receiver_online: boolean;
}

/** The payload CBOR-encoded inside the server's COSE_Sign1 receipt.
 *
 * `recipient_device_id` and `receiver_nonce` bind the receipt to a specific
 * payee -- without them, a receipt is nothing more than a server-signed
 * assertion that "some payment of this amount settled under this tx_uuid",
 * verifiable by anyone but not bound to any party. That made it a bearer
 * token: an attacker could settle a self-payment under a tx_uuid, then
 * relay that same genuinely-valid receipt as if it were a completely
 * different transaction to an unrelated recipient (worse than disclosure --
 * settlement forgery, no money ever reaching the real recipient). Found via
 * /security-review alongside the transfer()-level tx_uuid conflict guard
 * (server/src/adapters/MockBankAdapter.ts) -- same underlying issue,
 * client/attacker-suppliable identifiers insufficiently bound to what they
 * should be scoped to, see CLAUDE.md §5.
 *
 * `receiver_nonce` is all-zero (16 bytes) for Mode C, which has no nonce
 * concept in OfflineIou -- the recipient binding alone is Mode C's
 * protection; see server/src/routes/sync.ts's context passthrough. */
export interface TxReceipt {
  tx_uuid: Uint8Array;
  settled_at: number; // unix ms
  amount: bigint;
  currency: string;
  recipient_device_id: Uint8Array; // 16 bytes
  receiver_nonce: Uint8Array; // 16 bytes, all-zero for Mode C
}

/**
 * Mode C's signed IOU payload (spec §5: `{amount, recipient_id, tx_uuid, seq, ts}`).
 * Field naming reconciled with TxProposal for consistency -- the spec's
 * `recipient_id` and this project's existing `recipient_device_id` (TxProposal)
 * refer to the same thing (a device_id resolved to an account server-side), so
 * this uses `recipient_device_id` too rather than introducing a second name for
 * an identical lookup pattern.
 *
 * `seq` is this device's per-signing-key monotonic counter (compared against
 * `devices.last_seq` server-side at /tx/sync) -- the anti-rollback mechanism ADV-03
 * exercises. It is NOT itself trusted client-side bookkeeping; only the server's
 * tracked last_seq is authoritative.
 *
 * The freshness_token (a separate, server-signed FreshnessToken below) travels
 * alongside this payload at /tx/sync, not inside it -- keeping this array's wire
 * shape matching the spec's 5-field list exactly.
 */
export interface OfflineIou {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  recipient_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string;
  seq: bigint; // matches devices.last_seq's BIGINT
  ts: number; // unix ms, device clock at signing time
}

/**
 * The payload CBOR-encoded inside a server-signed freshness token
 * (GET /devices/:deviceId/freshness-token). Proves "this device successfully
 * reached the server at issued_at" -- a server-attested fact a client can't
 * forge or backdate, used to bound how stale an offline (Mode C) IOU is allowed
 * to be (spec §5: "payer holds a freshness_token issued within 24h").
 */
export interface FreshnessToken {
  device_id: Uint8Array; // 16 bytes
  issued_at: number; // unix ms, SERVER clock
}

/**
 * Purely informational -- NOT signed, NOT verifiable on its own. Shown by a
 * Mode C payer (as a second QR, right after signing an OfflineIou) so the
 * payee can locally track "I'm expecting this" without any cryptographic
 * claim being made yet. The payee's only independently-verifiable proof of
 * settlement is later checking GET /tx/:txUuid/receipt and verifying that
 * server-signed receipt against the pinned server key -- exactly what a Mode
 * B payee already does. This type exists so that check has a real, tested
 * wire format instead of ad hoc JSON riding in a QR code.
 */
export interface IncomingIouInfo {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string;
}

/**
 * The payload CBOR-encoded inside a server-signed device credential
 * (GET /devices/:deviceId/credential). Lets a peer verify "this identity_pubkey
 * really belongs to this enrolled device" offline, against the pinned server
 * key -- the precondition authenticated session ECDH (CLAUDE.md §5's "code that
 * does not exist yet" block) needs before deriving a shared secret. The server
 * refuses to issue this at all unless attestation_ok, so `attestation_ok` is
 * deliberately not a field here -- carrying it would let a client make its own
 * trust decision instead of the credential's mere existence being the decision.
 */
export interface DeviceCredential {
  device_id: Uint8Array; // 16 bytes
  identity_pubkey: Uint8Array; // 33-byte SEC1-compressed P-256
  issued_at: number; // unix ms, SERVER clock
}

/**
 * Authenticated session ECDH's signed handshake message (CLAUDE.md §5's "code
 * that does not exist yet" block -- being built ahead of the rest of M3 as a
 * transport-agnostic layer). Each side generates an ephemeral P-256 key pair
 * for one transaction and signs this WHOLE struct with its hardware identity
 * key, not just the bare ephemeral pubkey: a signature over only the key could
 * be lifted into a different transaction, so `tx_uuid` and `device_id` are
 * bound inside the signed bytes, the same discipline the receiver nonce
 * already gets inside TxProposal. See crypto/session.ts's deriveSessionKey for
 * how a verified hello becomes a shared session key.
 */
export interface SessionHello {
  tx_uuid: Uint8Array; // 16 bytes
  device_id: Uint8Array; // 16 bytes -- the sender of THIS hello, not the peer
  eph_pubkey: Uint8Array; // 33-byte SEC1-compressed P-256, this session only
  ts: number; // unix ms, device clock at signing time
  /** The sender's own server-signed DeviceCredential (GET
   * /devices/:deviceId/credential's COSE_Sign1 response bytes, verbatim),
   * carried inline so the receiving side can verify "this identity_pubkey
   * really belongs to this device" purely offline against the pinned server
   * key -- no live fetchPeerCredential network call needed on either side
   * (M3 Milestone 3: found via live two-phone testing that requiring a live
   * fetch broke BLE settlement the moment either party went offline, even
   * though the radio connection itself didn't need one). Trust still comes
   * entirely from the server's own signature over this credential, not from
   * how it arrived -- see deriveSessionKey/verifyEmbeddedCredential
   * (session.ts). Required, not legacy-tolerant: this is pre-release code
   * with no deployed old-format clients to support. */
  own_credential: Uint8Array;
}

/** Terminal + in-flight states for a Mode C intent, mirrored on both the server's
 * offline_intents table and the client's local SQLite queue. */
export type OfflineSyncStatus =
  | "PENDING"
  | "SETTLED"
  | "FAILED_INSUFFICIENT"
  | "FAILED_EXPIRED"
  | "FAILED_SEQUENCE_REGRESSION"
  | "FAILED_CONFLICT";

/** Spec §5's mode-selection rule, verbatim: receiver-online wins first (Mode A,
 * canonical/zero-risk), then sender-online (Mode B, bridge), else Mode C. */
export function evaluateConnectivity(receiverOnline: boolean, senderOnline: boolean): ConnectivityMode {
  if (receiverOnline) return ConnectivityMode.MODE_A;
  if (senderOnline) return ConnectivityMode.MODE_B;
  return ConnectivityMode.MODE_C;
}
