/** The IBankAdapter seam (spec §2.1). A real bank would implement this with zero
 * changes above it — MockBankAdapter (server/src/adapters) is the only implementation
 * for MVP. Money is always bigint minor units; never a float anywhere in this file.
 */

export interface ReservationResult {
  success: boolean;
  reservationId?: string;
  failureReason?: string;
}

export interface CommitResult {
  success: boolean;
  settledAt: Date;
  /** COSE_Sign1 bytes, signed by the server identity key (packages/shared/src/crypto). */
  receiptSignature: Uint8Array;
  failureReason?: string;
}

export interface IBankAdapter {
  getAvailableBalance(accountId: string, currency: string): Promise<bigint>;
  reserve(
    txUuid: string,
    accountId: string,
    amount: bigint,
    currency: string,
    ttlSeconds: number,
  ): Promise<ReservationResult>;
  commit(txUuid: string): Promise<CommitResult>;
  release(txUuid: string): Promise<void>;
  transfer(
    txUuid: string,
    fromAccountId: string,
    toAccountId: string,
    amount: bigint,
    currency: string,
  ): Promise<CommitResult>;
}

/** Stub for M2 — evaluateConnectivity() ships with Mode B/C in the M2 milestone. */
export enum ConnectivityMode {
  MODE_A = "RECEIVER_ONLINE",
  MODE_B = "SENDER_ONLINE",
  MODE_C = "BOTH_OFFLINE",
}

/**
 * The payload CBOR-encoded inside the COSE_Sign1 signature (packages/shared/src/crypto/cose.ts).
 * Device ids and tx_uuid are raw 16-byte UUID bytes, not string form, to keep the
 * signed payload (and the QR code carrying it, per M1 Step 9) small — string UUIDs
 * would cost more than double for no security benefit.
 *
 * `ts` freshness policy (decided in M1 planning, not left decorative): the server
 * rejects proposals whose `ts` falls outside a generous, config-driven window at
 * /tx/submit. This is a coarse sanity bound, layered *behind* tx_uuid idempotency
 * (the actual replay defense) — not a replacement for it. Kept consistent with
 * Mode C's 24h freshness_token concept arriving in M2.
 */
export interface TxProposal {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  recipient_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string; // ISO 4217-style, 3 chars, "MAD" for MVP
  receiver_nonce: Uint8Array; // 16 bytes, generated by the payee (Request QR)
  ts: number; // unix ms
}

/** The payload CBOR-encoded inside the server's COSE_Sign1 receipt. */
export interface TxReceipt {
  tx_uuid: Uint8Array;
  settled_at: number; // unix ms
  amount: bigint;
  currency: string;
}

/**
 * Mode C's signed IOU payload (spec §5: `{amount, recipient_id, tx_uuid, seq, ts}`).
 * Field naming reconciled with TxProposal for consistency -- the spec's
 * `recipient_id` and this project's existing `recipient_device_id` (TxProposal)
 * refer to the same thing (a device_id resolved to an account server-side), so
 * this uses `recipient_device_id` too rather than introducing a second name for
 * an identical lookup pattern.
 *
 * `seq` is this device's per-signing-key monotonic counter (compared against
 * `devices.last_seq` server-side at /tx/sync) -- the anti-rollback mechanism ADV-03
 * exercises. It is NOT itself trusted client-side bookkeeping; only the server's
 * tracked last_seq is authoritative.
 *
 * The freshness_token (a separate, server-signed FreshnessToken below) travels
 * alongside this payload at /tx/sync, not inside it -- keeping this array's wire
 * shape matching the spec's 5-field list exactly.
 */
export interface OfflineIou {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  recipient_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string;
  seq: bigint; // matches devices.last_seq's BIGINT
  ts: number; // unix ms, device clock at signing time
}

/**
 * The payload CBOR-encoded inside a server-signed freshness token
 * (GET /devices/:deviceId/freshness-token). Proves "this device successfully
 * reached the server at issued_at" -- a server-attested fact a client can't
 * forge or backdate, used to bound how stale an offline (Mode C) IOU is allowed
 * to be (spec §5: "payer holds a freshness_token issued within 24h").
 */
export interface FreshnessToken {
  device_id: Uint8Array; // 16 bytes
  issued_at: number; // unix ms, SERVER clock
}

/**
 * Purely informational -- NOT signed, NOT verifiable on its own. Shown by a
 * Mode C payer (as a second QR, right after signing an OfflineIou) so the
 * payee can locally track "I'm expecting this" without any cryptographic
 * claim being made yet. The payee's only independently-verifiable proof of
 * settlement is later checking GET /tx/:txUuid/receipt and verifying that
 * server-signed receipt against the pinned server key -- exactly what a Mode
 * B payee already does. This type exists so that check has a real, tested
 * wire format instead of ad hoc JSON riding in a QR code.
 */
export interface IncomingIouInfo {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string;
}

/** Terminal + in-flight states for a Mode C intent, mirrored on both the server's
 * offline_intents table and the client's local SQLite queue. */
export type OfflineSyncStatus =
  | "PENDING"
  | "SETTLED"
  | "FAILED_INSUFFICIENT"
  | "FAILED_EXPIRED"
  | "FAILED_SEQUENCE_REGRESSION";

/** Spec §5's mode-selection rule, verbatim: receiver-online wins first (Mode A,
 * canonical/zero-risk), then sender-online (Mode B, bridge), else Mode C. */
export function evaluateConnectivity(receiverOnline: boolean, senderOnline: boolean): ConnectivityMode {
  if (receiverOnline) return ConnectivityMode.MODE_A;
  if (senderOnline) return ConnectivityMode.MODE_B;
  return ConnectivityMode.MODE_C;
}
