/** The IBankAdapter seam (spec §2.1). A real bank would implement this with zero
 * changes above it — MockBankAdapter (server/src/adapters) is the only implementation
 * for MVP. Money is always bigint minor units; never a float anywhere in this file.
 */

export interface ReservationResult {
  success: boolean;
  reservationId?: string;
  failureReason?: string;
}

export interface CommitResult {
  success: boolean;
  settledAt: Date;
  /** COSE_Sign1 bytes, signed by the server identity key (packages/shared/src/crypto). */
  receiptSignature: Uint8Array;
  failureReason?: string;
}

export interface IBankAdapter {
  getAvailableBalance(accountId: string, currency: string): Promise<bigint>;
  reserve(
    txUuid: string,
    accountId: string,
    amount: bigint,
    currency: string,
    ttlSeconds: number,
  ): Promise<ReservationResult>;
  commit(txUuid: string): Promise<CommitResult>;
  release(txUuid: string): Promise<void>;
  transfer(
    txUuid: string,
    fromAccountId: string,
    toAccountId: string,
    amount: bigint,
    currency: string,
  ): Promise<CommitResult>;
}

/** Stub for M2 — evaluateConnectivity() ships with Mode B/C in the M2 milestone. */
export enum ConnectivityMode {
  MODE_A = "RECEIVER_ONLINE",
  MODE_B = "SENDER_ONLINE",
  MODE_C = "BOTH_OFFLINE",
}

/**
 * The payload CBOR-encoded inside the COSE_Sign1 signature (packages/shared/src/crypto/cose.ts).
 * Device ids and tx_uuid are raw 16-byte UUID bytes, not string form, to keep the
 * signed payload (and the QR code carrying it, per M1 Step 9) small — string UUIDs
 * would cost more than double for no security benefit.
 *
 * `ts` freshness policy (decided in M1 planning, not left decorative): the server
 * rejects proposals whose `ts` falls outside a generous, config-driven window at
 * /tx/submit. This is a coarse sanity bound, layered *behind* tx_uuid idempotency
 * (the actual replay defense) — not a replacement for it. Kept consistent with
 * Mode C's 24h freshness_token concept arriving in M2.
 */
export interface TxProposal {
  tx_uuid: Uint8Array; // 16 bytes
  sender_device_id: Uint8Array; // 16 bytes
  recipient_device_id: Uint8Array; // 16 bytes
  amount: bigint;
  currency: string; // ISO 4217-style, 3 chars, "MAD" for MVP
  receiver_nonce: Uint8Array; // 16 bytes, generated by the payee (Request QR)
  ts: number; // unix ms
}

/** The payload CBOR-encoded inside the server's COSE_Sign1 receipt. */
export interface TxReceipt {
  tx_uuid: Uint8Array;
  settled_at: number; // unix ms
  amount: bigint;
  currency: string;
}
